/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package krusher

import kotlin.test.Test
import kotlin.test.assertTrue

class KrusherTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Krusher()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
